### ISSUE TITLE
iostream support

### ISSUE THREAD

**Issue by AaronDMarasco-VSI** [msharov/ustl#14]
I am trying to migrate a large existing project to uSTL, and it uses `iostream`s. It seems that uSTL only supports input or output streams, but not both.

A quick look at the GNU STL seems to imply it is very straightforward: simply have the two "halves" point to the same underlying `basic_streambuf`, but uSTL doesn't have that buffer abstraction layer, so I wasn't able to quickly piece one together with my limited understanding of the uSTL internals.

Is this something that is intentionally left out? Is there a rough equivalent already available? Thanks!

**Comment by msharov** [comment]
That will not do what you think it will do. uSTL streams do not have streambufs and so will generally not be usable by projects built around that sort of thing. If you want a stream class that can read and write a file, which is the only thing you can be thinking of since you have not asked for basic_streambuf implementation yet, you'll need to create iostream class derived from both istringstream and ostringstream and containing an fstream (see ofstream.h for ifstream and ofstream that form the base for cin and cout), deal with the horrible diamond inheritance problems this will create, implement whatever the standard specifies for its interface by forwarding to the appropriate base, and send me a patch. This is all going to be quite a bit of work, and I am just not interested in undertaking it at this time. I'll leave the issue open in case you or somebody else wants to do it.

**Comment by AaronDMarasco-VSI** [comment]
OK, thanks for the info.

**Comment by msharov** [comment]
Could you please post a usage example for iostream? I have not been able to find a single one; all streams examples use either input or output streams, never both. I would at the very least have to write a test case for iostream, and I have a really hard time coming up with any realistic use case. For binary files, I can imagine keeping a database file open and reading and writing parts of it, but this would not work with a text file.

**Comment by msharov** [comment]
Since this will inevitably cause code size increase and with no one sufficiently interested to even provide a test case, I'm going to postpone implementation until that changes.
