### ISSUE TITLE
Restructure source tree to allow recursive grep/search

### ISSUE THREAD

**Issue by mingodad** [msharov/ustl#25]
Hello !
The actual way the source tree is organized present some drawbacks after running make once. After running make at least once a symbolic link is created "ustl" pointing to itself, when this symbolic link is present some tools/editors (for example scite) that preform a recursive search go mad in near infinite recursion loop. Also on platforms where there is no symbolic link it'll not work (for example windows, not ported yet).

So I propose to move the ustl sources to real folder "ustl".

Cheers !

**Comment by msharov** [comment]
If scite goes into infinite loop on symbolic links, it is a problem with scite and you should submit a bug report there. The uSTL source tree is certainly not the only place where such a situation can be encountered.

Windows is not and will not be supported. We should all do our part to discourage the existence of Windows.

And as for moving sources into a ustl subdir, rejected. Yes, the symlink could in principle be removed. It is only there for the bvts, which could include in-tree headers directly instead of using ustl.h. But presently there is no reason to do so.
