### ISSUE TITLE
disabling -march=native in configure

### ISSUE THREAD

**Issue by darealshinji** [msharov/ustl#53]
Can you add an option in the configure script to disable `-march=native` being added to the build flags?

**Comment by msharov** [comment]
Why? I already only enable it for gcc versions that support it. In any case, it would be better to detect the platform on which it is a problem and disable it automatically.

**Comment by darealshinji** [comment]
I read that `-march=native` might result in binaries which won't run on older CPUs not supporting some of the used optimizations. I'm interested in using ustl as a tiny statically linked in library to generate portable binaries and I just want to avoid incompatibility if possible.

**Comment by msharov** [comment]
You are basically talking about cross-compiling to a different platform. uSTL does not currently support that. It is not just -march=native; there are various other configure checks that result in libustl being targeted at the system being compiled. Making cross-compilation work requires a lot of effort and an old system to test on. If you have the latter and are willing to do the former, I'll take a patch enabling --target configure switch. Until that is done, it is simpler to recommend editing Config.mk for unusual cases like this.

**Comment by technosaurus** [comment]
This one never should have been closed.  It has nothing to do with cross compiling.  `-march=native` is improper for building a library for distribution since the distro build box may have the latest "ICKY-ICKY-PATANG-ZOOM-WAP" processor (a version of x86_64).  For every other package in the repository which smartly omits `-march=native`, the package will be built so that it can run on any x86_64 because the compiler will only emit basic x86, MMX, SSE and SSE2 instructions.  When you go putting  `-march=native` into default settings, you get crap like AVX-512 instructions in a library that is intended for general distribution on generic x86_64 systems (that probably don't have AVX2, much less AVX-512) or a statically compiled foo_viewer that won't work on 99% of systems even though it was compiled on an X86_64 box because the compiler noticed that the host has `foo_init` and `foo_iter` instructions and thus emitted those instructions in the binary.

Not to mention  `-march=native` isn't even a standard option across compilers or even architectures within gcc (it was only added for arm recently and many others architectures don't have it at all, so you'll always get a build failure on those architectures) 

This is one of those flags that you put in the documentation for people to add to their own CFLAGS if they want to build a static, maximally optimized, unportable version for internal use (basically gentoo users).   Otherwise it should be put in BOLD letters that the default configuration produces non-portable code.
