### ISSUE TITLE
missing functionality in unique_ptr/shared_ptr

### ISSUE THREAD

**Issue by goniz** [msharov/ustl#54]
Hi

I am missing the deleter options for the smart pointers you provide.
Real world applications requires both unique_ptr and shared_ptr to implement deleter functionality to actually work.
having deleters will allow you to add unique_ptr\<T\>(unique_ptr\<U\>&&) constructor + dynamic_pointer_cast/static_pointer_cast/etc..

It is way harder to actually use ustl with complex code using smart pointers.

I'm also missing the operator==(nullptr_t, *_ptr\<T\>) functions..

Thank you!

**Comment by msharov** [comment]
Deleters also make the unique_ptr larger, which is a bad thing for a project focusing on size optimization. Deleters are also an uncommon use case. Therefore, rejected.

Constructing from a different pointer type is also a bad idea. If you want a unique_ptr<T>, then give it a T pointer. If you are trying to do polymorphism, construct unique_ptr<T> directly with new U instead of make_unique or just write your own make_unique_T variant. There is no need to bloat uSTL with functionality that nobody should be using anyway.

Adding the top-level operators is not out of the question, however much I find them distasteful. I do after all, already have a few. But postponed for now.

**Comment by msharov** [comment]
Commit 8d65b14de61606315bb0f3f41eae1a4b47fc8eda adds unique_resource template, which can be used to implement your custom deleter scenario.

**Comment by goniz** [comment]
Thank you very much, looks good so far!

**Comment by goniz** [comment]
Just wanted to ask here before opening a new issue, shouldn't shared_ptr be implemented with atomics for the refcount? it should be fairly easy and compact with ustl::atomic.
I would like to hear you opinion on this. thanks.

**Comment by msharov** [comment]
Ok. Commit a508af083a3e0b9a8df21767af7dab9a25fffb7c.

**Comment by goniz** [comment]
Wow, that was fast.
Are you a ninja?

**Comment by msharov** [comment]
No, merely unemployed.
