### ISSUE TITLE
Replace stdc++ with ustl with minimal code changes

### ISSUE THREAD

**Issue by mwarning** [msharov/ustl#6]
It would be useful to replace stdc++ using ustl without changing the applications source.
This would be less intrusive to bigger applications and save a lot of work.

**Comment by mwarning** [comment]
I try compile a bigger project, but adding ustl includes to every file is tedious and has no chance to get upstream.

**Comment by msharov** [comment]
uSTL was always intended to be an alternative implementation, not a drop-in replacement. Heck, until only a few years ago, the API was different enough to require some serious thought before even considering it. It still does, due to the different behavior of the containers. The requirement to never have object self-pointers may be a big problem for some people's designs. Linking of strings (const char* ctor), may cause behavior you wouldn't expect if you didn't know about it. list, map, and set are defined as linked containers in libstdc++ and have different iterator invalidation semantics. So no, uSTL is definitely not a drop-in replacement for libstdc++. It is more of an alternative you choose before starting on your project, and before doing that it is a very good idea to read the docs and decide whether uSTL's design philosophy agrees with yours. It is entirely possible, it just isn't for you.

**Comment by msharov** [comment]
Looking at your efforts at making ZeroTierOne use uSTL, I can tell you right now that it will not work. A cursory look at some of the source files reveals dependencies on linked iterator semantics. For example, here is the code from node/Network.cpp:

for(std::map<Address,uint64_t>::iterator lp(_lastPushedMembershipCertificate.begin());lp!=_lastPushedMembershipCertificate.end();) {
    if (lp->second < forgetIfBefore)
        _lastPushedMembershipCertificate.erase(lp++);
    else ++lp;
}

Because in libstdc++ map is a linked container, lp++ in the erase call will point to a valid node - the next one. Linked container erase will invalidate only the iterators referring to the erased elements, leaving lp valid. uSTL's map is implemented as vector<pair<K,V>>, so after erase, lp++ will point to the second element after the erased one. In the best case, you'll end up erasing every other certificate. In the worst, you'll end up in an infinite loop because the for exit condition compares for equality with end() rather than < end(), and one of the lp++ may increment the iterator past the end after the erase.

The uSTL documentation explicitly warns about linked containers using vector's invalidation semantics, so I take it you have not actually read the uSTL web page (or doc/index.html) in full. Please do so before you get yourself into even more trouble :)

As I said, uSTL has a pecular design, created to fulfill a specific objective - smaller code size. This required making certain design choices that ensure that uSTL is not fully compliant with the C++ standard document. It can not be made fully compliant because doing so would make it identical to libstdc++; the template bloat and the other problems with it that uSTL addresses exist due to the design as specified in the standard, not a bad implementation. Reimplementing the same design would give more or less the same results as libstdc++ already delivers, in which case you may as well use libstdc++ - it is stable, well-maintained, and performant.
