### ISSUE TITLE
ustl::size_t and ustl::ptrdiff_t missing

### ISSUE THREAD

**Issue by mwarning** [msharov/ustl#7]
I replace libstdc++ with libustl and wrap ustl into the std namespace. 
This causes errors because for some application that use std::size_t nd std::ptrdiff_t.

That's why it would be nice to have ustl::size_t and ustl::ptrdiff_t defined using the (identical) c definition.

**Comment by msharov** [comment]
I don't think I can do this. utypes.h includes sys/types.h, where these two constants are supposed to be defined. Because the expected usage is to put "using namespace ustl" (you know, because using std:: this and std:: that everywhere is just plain stupid) everywhere, defining size_t and ptrdiff_t in ustl:: would cause an ambiguity. An no, I never liked the idea of replacing C headers with C++-specific ones. I understand this would make uSTL rather difficult to use for you project, but creating the ambiguity would make it more difficult to use for everybody else, so you may want to consider just sticking with libstdc++.

**Comment by jwakely** [comment]
> I don't think I can do this. utypes.h includes sys/types.h, where these two constants are supposed to be defined. Because the expected usage is to put "using namespace ustl" (you know, because using std:: this and std:: that everywhere is just plain stupid) everywhere, defining size_t and ptrdiff_t in ustl:: would cause an ambiguity.

No it wouldn't.

```c++
#include <stddef.h>

namespace ustl {
    using ::size_t;
}
using namespace ustl;
size_t s;
```

This is fine, there's no ambiguity because they're the same type.

**Comment by mwarning** [comment]
oh wow, i can hardly remember having created the ticket anymore.

**Comment by jwakely** [comment]
Yeah sorry, I'm looking at very old tickets!

**Comment by msharov** [comment]
Digging up decade old tickets in an obsolete project I keep trying to get people to stop using does seem rather pointless. But, ok; as long as you're having fun... :) As someone who maintains fifty year old games, I suppose I can relate to digital archaeology.
