### ISSUE TITLE
vector resize() non-standard

### ISSUE THREAD

**Issue by LinuxEngr** [msharov/ustl#80]
For the vector template:

c++11:  void resize (size_type n, const value_type& val);
c++98:  void resize (size_type n, value_type val = value_type());

ustl has: void resize (size_type n, bool bExact)

**Comment by msharov** [comment]
Not so much non-standard, as not implemented. The resize with specific value is not implemented and can not be due to value_type argument creating a compile-time ambiguity with bExact. So this is a "won't fix" due to backward compatibility breakage. You can work around with resize(n), fill(ctr,val).

**Comment by LinuxEngr** [comment]
Sigh. Is backward compatibility really more important than moving forward with standards compliance? Unfortunately the current version caused me some grief on a vector of an integer type that was ported to use ustl and then failed at runtime (in subtle ways due to new values not being initialized) because the resize() matched but didn't conform. Changing all the uses to resize()+fill() is not such a good way to move forward since it will need to be done for all code that uses resize() even in the future. I have code that is worked on by other folks and we normally run it on Linux with GNU, sometimes we re-build using ustl. An extra step of having to look for uses of resize() that will break is cumbersome, of course.

**Comment by msharov** [comment]
In a library that has been around for fifteen years with pretty much the same API? Yes, backward compatibility is important.

uSTL was never intended as a direct replacement for libstdc++. You never could just compile your project with it and expect it to work with both equally well. You still can't. There are many nonstandard behaviors that will break your project even if your code is fully standard compilant.

These behaviors exist intentionally, as I wrote uSTL because I disliked so many things about the standard and the general mindset it expected in programs using it. I cared about program size and my methods, while totally non-standard, have given me what I wanted. But this all comes from having an entirely different approach to writing C++ code and, as I state in the uSTL documentation, you may not agree with it.

You also may not gain all that much benefit either. If you look at the current size benchmarks at the bottom of uSTL's web page, you will see that the size savings are significantly smaller now than they used to be. Most of them now come from simply not linking with libstdc++. Consequently, I can no longer honestly recommend uSTL to anybody. I myself have not used it in over ten years. If you have an existing project with heavy STL use, I would definitely recommend you avoid uSTL altogether. It will not help you.

**Comment by msharov** [comment]
Sigh. Oh, screw it. I just don't care enough. Reopening.

**Comment by msharov** [comment]
Fixed by commit be524cca98e171bead59cab8393e416896b25901
