### ISSUE TITLE
USTL array missing methods

### ISSUE THREAD

**Issue by mingodad** [msharov/ustl#97]
Hello !
Continuing to test ustl now I'm trying to compile https://github.com/Tessil/array-hash see attached:
[array-hash.zip](https://github.com/msharov/ustl/files/2531133/array-hash.zip)

USTL is including the header "<initializer_list>", in the past we could swap "std/ustl" using namespace but today with USTL also using "std::execption" it's not possible anymore and we need to use a neutral namespace alias like "lstd" to be able to swap between then. Is this accidental or it's a conscious choice ?
This implementation of array_map could be a good addition to USTL it's faster than std and uses less memory.

Cheers !
```
./test-mk
In file included from include/tsl/array_hash.h:48:0,
                 from include/tsl/array_map.h:41,
                 from test.cpp:22:
include/tsl/array_growth_policy.h: In member function ‘size_t tsl::ah::mod_growth_policy<GrowthFactor>::next_bucket_count() const’:
include/tsl/array_growth_policy.h:158:13: error: ‘isnormal’ is not a member of ‘lstd’
         if(!lstd::isnormal(next_bucket_count)) {
             ^
include/tsl/array_growth_policy.h:158:13: note: suggested alternative:
In file included from include/tsl/array_hash.h:43:0,
                 from include/tsl/array_map.h:41,
                 from test.cpp:22:
/usr/include/c++/5/cmath:670:5: note:   ‘std::isnormal’
     isnormal(_Tp __x)
     ^
In file included from include/tsl/array_hash.h:48:0,
                 from include/tsl/array_map.h:41,
                 from test.cpp:22:
include/tsl/array_growth_policy.h: In member function ‘size_t tsl::ah::prime_growth_policy::max_bucket_count() const’:
include/tsl/array_growth_policy.h:262:31: error: ‘const class ustl::array<long unsigned int, 39ul>’ has no member named ‘back’
         return detail::PRIMES.back();
                               ^
In file included from include/tsl/array_map.h:41:0,
                 from test.cpp:22:
include/tsl/array_hash.h: In member function ‘ustl::pair<tsl::detail_array_hash::array_hash<CharT, T, Hash, KeyEqual, StoreNullTerminator, KeySizeT, IndexSizeT, GrowthPolicy>::array_hash_iterator<false>, tsl::detail_array_hash::array_hash<CharT, T, Hash, KeyEqual, StoreNullTerminator, KeySizeT, IndexSizeT, GrowthPolicy>::array_hash_iterator<false> > tsl::detail_array_hash::array_hash<CharT, T, Hash, KeyEqual, StoreNullTerminator, KeySizeT, IndexSizeT, GrowthPolicy>::equal_range(const CharT*, tsl::detail_array_hash::array_hash<CharT, T, Hash, KeyEqual, StoreNullTerminator, KeySizeT, IndexSizeT, GrowthPolicy>::size_type, size_t)’:
include/tsl/array_hash.h:1158:53: error: ‘next’ is not a member of ‘lstd’
         return lstd::make_pair(it, (it == end())?it:lstd::next(it));
                                                     ^
include/tsl/array_hash.h: In member function ‘ustl::pair<tsl::detail_array_hash::array_hash<CharT, T, Hash, KeyEqual, StoreNullTerminator, KeySizeT, IndexSizeT, GrowthPolicy>::array_hash_iterator<true>, tsl::detail_array_hash::array_hash<CharT, T, Hash, KeyEqual, StoreNullTerminator, KeySizeT, IndexSizeT, GrowthPolicy>::array_hash_iterator<true> > tsl::detail_array_hash::array_hash<CharT, T, Hash, KeyEqual, StoreNullTerminator, KeySizeT, IndexSizeT, GrowthPolicy>::equal_range(const CharT*, tsl::detail_array_hash::array_hash<CharT, T, Hash, KeyEqual, StoreNullTerminator, KeySizeT, IndexSizeT, GrowthPolicy>::size_type, size_t) const’:
include/tsl/array_hash.h:1165:54: error: ‘next’ is not a member of ‘lstd’
         return lstd::make_pair(it, (it == cend())?it:lstd::next(it));
                                                      ^
include/tsl/array_hash.h: In member function ‘void tsl::detail_array_hash::array_hash<CharT, T, Hash, KeyEqual, StoreNullTerminator, KeySizeT, IndexSizeT, GrowthPolicy>::clear_old_erased_values()’:
include/tsl/array_hash.h:1293:34: error: ‘move_if_noexcept’ is not a member of ‘lstd’
             new_values.push_back(lstd::move_if_noexcept(it.value()));
                                  ^
In file included from test.cpp:22:0:
include/tsl/array_map.h: At global scope:
include/tsl/array_map.h:126:37: error: expected ‘)’ before ‘<’ token
     array_map(lstd::initializer_list<lstd::pair<const CharT*, T>> init,
                                     ^
include/tsl/array_map.h:146:32: error: declaration of ‘operator=’ as non-function
     array_map& operator=(lstd::initializer_list<lstd::pair<const CharT*, T>> il
                                ^
include/tsl/array_map.h:146:24: error: expected ‘;’ at end of member declaration
     array_map& operator=(lstd::initializer_list<lstd::pair<const CharT*, T>> il
                        ^
include/tsl/array_map.h:146:48: error: expected ‘)’ before ‘<’ token
     array_map& operator=(lstd::initializer_list<lstd::pair<const CharT*, T>> il
                                                ^
include/tsl/array_map.h:252:23: error: ‘lstd::initializer_list’ has not been declared
     void insert(lstd::initializer_list<lstd::pair<const CharT*, T>> ilist) {
                       ^
include/tsl/array_map.h:252:39: error: expected ‘,’ or ‘...’ before ‘<’ token
     void insert(lstd::initializer_list<lstd::pair<const CharT*, T>> ilist) {
                                       ^
include/tsl/array_map.h: In member function ‘void tsl::array_map<CharT, T, Hash, KeyEqual, StoreNullTerminator, KeySizeT, IndexSizeT, GrowthPolicy>::insert(int)’:
include/tsl/array_map.h:253:16: error: ‘ilist’ was not declared in this scope
         insert(ilist.begin(), ilist.end());
                ^
```

**Comment by msharov** [comment]
The use of std:: for initializer_list and exception is intentional and required for the compiler to recognize them and use the properly.

isnormal is part of cmath, which I do not intend to implement. Stop hating C headers and use math.h.

move_if_noexcept breaks expectations; you either move an element or you don't, and move_if_noexcept makes that dependent on type, requiring library users to examine its internals. That is always a bad thing.

next and prev, and have no idea what those are supposed to be for. Just ++iterator, like all the other STL code has done for decades.

So no, I don't want to implement any of these.

**Comment by msharov** [comment]
I do appreciate all the testing you do for the library; finding all these bugs is a good thing. It is not, however, a good thing to just pick random projects and push them to use uSTL. As I have pointed out in the documentation, there exist significant differences that library users must be aware of, such as iterator invalidation semantics, the moveable object requirement, the linking behavior, etc. Not being the author of these projects, you would not be able to determine whether these differences would cause problems. The stylistic differences you keep finding strongly suggest otherwise, as these projects were obviously designed by following the guidelines commonly taught in the academia today. Guidelines that specify a very different role and purpose for the standard library than what I designed uSTL for. As I explain in the documentation, uSTL would be a better fit for a "C with classes" programming style and projects using it would work best if they were designed specifically with that in mind.

Furthermore, with the space savings having been considerably reduced when compared with the current gcc libstdc++, I would no longer recommend anybody to use uSTL at all. Sometime in the near future I'll probably deprecate the project altogether and post a notice on the web page stating that this libarary is obsolete and people should move on to libstdc++.

**Comment by andrey-zibrov** [comment]
Hi Mike, (in case of disadvantages of this project) can you please clarify why did you recently said that this project is not a proper solution for the embedded directions like stm32f4 or anything more powerfull like rpi?

**Comment by msharov** [comment]
Embedded microcontrollers such as stm32 do not have enough memory to waste on C++ containers. On such platforms you typically do not even use dynamic memory at all, but rather preallocate the blocks you are going to use statically. If you use any C++, you would certainly not use anything from the standard library, simply because there is no room. Even uSTL in its tightest build is way too big to fit there.

As for the raspberry Pi, it is pretty much a normal Linux platform, where you can use anything you like. You should use the regular C++ standard library. uSTL had big space savings over libstdc++ back in 2003 when I first wrote it, but those savings pretty much disappeared by now. The major difference now is the size of the shared library, and it is irrelevant once you use any application linked to libstdc++, such as firefox, that will load it in memory anyway. Back in 2003 C++ apps were much scarcer and you could get by without them. Now, libstdc++ is used extensively and, being already in memory, is almost always the better choice.
